testproject/accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    url('^signup/$', views.signup_view, name='signup'),
    url('^login/$', views.login_view, name='login'),
    url('^logout/$', views.logout_view, name='logout'),
]

testproject/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url('^$', views.article_list, name='list'),
    url('^create/', views.article_create, name='create'),
    url('^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

testproject/testproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^articles/', include('articles.urls')),
    url('^accounts/', include('accounts.urls')),
    url('^about/$', views.about),
    url('^$', article_views.article_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/accounts/models.py
from django.db import models

# Create your models here.

testproject/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+"..."

testproject/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','thumb']

testproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('articles:list')

testproject/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def article_list(request):
    articles = Article.objects.all()
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url='/accounts/login')
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #Save Article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
        print("Its coming here lallu")
    return render(request, 'articles/article_create.html', {'form':form})

testproject/testproject/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

testproject/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <form class="login" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" name="login">
  </form>
{% endblock %}

testproject/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<form class="site-form" action="/accounts/signup/" method="post">
{% csrf_token %}
{{form}}
<input type="submit" name="signup">
</form>


{% endblock %}

testproject/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<h2>Create a New Article</h2>
<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Create">
</form>

{% endblock %}

testproject/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  <img src="{{article.thumb.url }}" />
  <h2>{{article.body}}</h2>
  <h3>{{article.date}}</h3>

{% endblock %}

testproject/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>
    <div class="article">
    {% for article in articles %}
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <h3>{{article.slug}}</h3>
        <h3>{{article.snippet}}</h3>
        <h3>{{article.date}}</h3>
    {% endfor %}
    </div>
{% endblock %}

testproject/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About Page</title>
  </head>
  <body>
    <h1>Welcome to About Page</h1>
  </body>
</html>

testproject/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Article List</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
        <li><a href="{% url 'articles:create' %}" class="highlight">New Article </a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

testproject/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    <h1>Welcome to Test area</h1>
  </body>
</html>