djangonautic/articles/urls.py
from django.conf.urls import url
from . import views


app_name = 'articles'

urlpatterns = [
        url('^$', views.article_list, name='list'),
        url('^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

djangonautic/djangonautic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.home),
    url('^articles/', include('articles.urls')),
    url('^about/$', views.about),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

djangonautic/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

djangonautic/djangonautic/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  <img src="{{article.thumb.url}}" />
  <h1>{{article.title}}</h1>
  <h2>{{article.body}}</h2>
  <h3>{{article.date}}</h3>
{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="wrapper">
      {% for article in articles %}
        <h1><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h1>
        <h2>{{article.slug}}</h2>
        <h3>{{article.snippet}}</h3>
        <h3>{{article.date}}</h3>
      {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About Page</title>
  </head>
  <body>
    <h1>About Page</h1>
  </body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Article List</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{% url 'articles:list' %}"><img src='{% static 'logo.png' %}'/></a></h1>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

djangonautic/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Welcome to DjangoNautic</h1>
  </body>
</html>