myfirstapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup_view'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

myfirstapp/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns=[
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>', views.article_detail, name='detail'),
]

myfirstapp/myfirstapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

myfirstapp/accounts/models.py
from django.db import models

# Create your models here.

myfirstapp/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='mobile.png', blank=True)
    author = models.ForeignKey(User, default=none, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

myfirstapp/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForms):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','thumb']

myfirstapp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    return render(request, 'signup.html', {'form': form})

def login_view(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('articles:list')

myfirstapp/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'article_list.html', {'articles': articles})

@login_required(login_url = '/accounts/login')
def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'article_detail.html', {'article':article})

def article_create(request):
    if forms.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/create_article.html', {'form':form})

myfirstapp/myfirstapp/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home_page.html')

myfirstapp/accounts/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <form class="login-site" action="{% url 'accounts:login_view' %}" method="post">
    <h1>Login Form</h1>
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value='Login'>
  </form>
{% endblock %}

myfirstapp/accounts/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Signup</h1>
    <form class="signup-site" action="{% url 'accounts:signup_view' %}" method="post">
      {% csrf_token %}
      {{form}}
      <input type="submit" name="signup">
    </form>
{% endblock %}

myfirstapp/articles/templates/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  <img src={{article.thumb.url}} />
  <h2>{{article.slug}}</h2>
  <h3>{{article.body}}</h3>
  <h4>{{article.date}}</h4>
{% endblock %}

myfirstapp/articles/templates/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1><a href="{% url 'articles:list' %}"><img src="/static/logo.png" class='logoimage'></a></h1>
    {% for article in articles %}
      <a href="{% url 'articles:detail' slug=article.slug %}"><h2>{{article.title}}</h2></a>
      <h3>{{article.slug}}</h3>
      <h4>{{article.snippet}}</h4>
      <h5>{{article.date}}</h5>
    {% endfor %}
{% endblock %}

myfirstapp/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Article List</title>
  </head>
  <body>
    <form class="" action="{% url 'accounts:logout_view' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Logout">
    </form>
    {% block content %}
    {% endblock %}
  </body>
</html>

myfirstapp/templates/home_page.html
<h1>Home Page</h1>